
import markdown
from xhtml2pdf import pisa
import os

def convert_md_to_pdf(source_md, output_pdf):
    # 1. Read Markdown file
    with open(source_md, 'r', encoding='utf-8') as f:
        text = f.read()

    # 2. Convert to HTML
    html_body = markdown.markdown(text)

    # 3. Add Styling
    html_content = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                font-size: 12pt;
                line-height: 1.6;
                color: #333;
            }}
            h1 {{
                color: #2c3e50;
                text-align: center;
                font-size: 24pt;
                margin-bottom: 20px;
                border-bottom: 2px solid #667eea;
                padding-bottom: 10px;
            }}
            h2 {{
                color: #667eea;
                font-size: 18pt;
                margin-top: 25px;
                margin-bottom: 15px;
                border-bottom: 1px solid #eee;
            }}
            h3 {{
                color: #764ba2;
                font-size: 14pt;
                margin-top: 20px;
                margin-bottom: 10px;
            }}
            p {{
                margin-bottom: 10px;
            }}
            li {{
                margin-bottom: 5px;
            }}
            code {{
                background-color: #f4f4f4;
                padding: 2px 5px;
                border-radius: 3px;
                font-family: Courier New, monospace;
            }}
            pre {{
                background-color: #f8f9fa;
                padding: 15px;
                border-radius: 5px;
                border: 1px solid #e9ecef;
            }}
            .footer {{
                text-align: center;
                font-size: 10pt;
                color: #777;
                margin-top: 50px;
                border-top: 1px solid #ddd;
                padding-top: 20px;
            }}
        </style>
    </head>
    <body>
        {html_body}
        <div class="footer">
            Generated by MediTrack Automated Reporting System
        </div>
    </body>
    </html>
    """

    # 4. Write to PDF
    with open(output_pdf, "wb") as result_file:
        pisa_status = pisa.CreatePDF(
            html_content, dest=result_file
        )

    if pisa_status.err:
        print(f"Error generating PDF: {pisa_status.err}")
    else:
        print(f"Successfully generated PDF: {output_pdf}")

if __name__ == "__main__":
    convert_md_to_pdf("PROJECT_REPORT.md", "MediTrack_Project_Report.pdf")
